version: 2
jobs:
  build:
    docker:
      - image: jguyomard/hugo-builder

    branches:
      ignore:
        - master

    steps:
      - checkout

      - run:
          name: build
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              hugo -d /tmp/output
              mv .circleci /tmp/output/
              git checkout master
              mv CNAME /tmp/output/
              rm -rf *
              mv /tmp/output/* .
              mv /tmp/output/.circleci .circleci
            fi

      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "docs" ]; then
              git config user.name "CircleCI Bot"
              git config user.email "circleci@circleci"
              git add --all
              git commit -m "automated build"
              git push -q
            fi
